package md.proj.encryptedchat.exception;

public enum ErrorType {
    PREKEY_NOT_PUBLISHED,
    AUTHENTICATION_FAILED,
    ACCOUNT_LOCKED,
    BLOCKCHAIN_CONNECTION_FAILED,
    CONTRACT_INTERACTION_FAILED,
    INTERNAL_SERVER_ERROR,
    RESOURCE_NOT_FOUND,
}
